apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v16
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v16
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v16
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v16
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.1.0
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=kubernetes
            - --metric_resolution=60s
